# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20160819_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='city',
        ),
        migrations.RemoveField(
            model_name='post',
            name='province',
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='province',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
