# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20160819_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='weibo_thumb_img',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
