# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import location.models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=location.models.image_path),
        ),
    ]
